name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  upload-artifact:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .

  deploy:
    needs: upload-artifact
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
